[package]
name = "ggez_test"
version = "0.1.0"
authors = ["flauntingspade4"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
noise = "0.6.0"
#ncollide2d = "0.22"
nphysics2d = "0.14.0"